### ISSUE TITLE
scibot can't find PMID/DOI on this page

### ISSUE THREAD

**Issue by anp055** [SciCrunch/scibot#25]
http://www.mdpi.com/2073-4425/9/4/197/htm

PMID is available and DOI is visible on page

**Comment by tgbugs** [comment]
https://hyp.is/17orGD3aEeievqORIoeKLA/www.mdpi.com/2073-4425/9/4/197
https://hyp.is/j612NLUUEeiRMc-zpgtbvg/www.mdpi.com/2073-4425/9/4/197

Looks ok to me. There may just be a time lag. Also it may not be appearing because mdpi doesn't have https on their site so your browser may be blocking hypothesis and scibot access due to the conflict.
